In [7]:
import numpy as np

In [1]:
class Test():
    def __init__(self):
        self.n = 1000

    def selfn(self):

        for i in range(10000):
            self.n = self.n = 1

    def notselfn(self):
        n = self.n

        for i in range(10000):
            n = n + 1


test = Test()

In [4]:
%timeit test.selfn()

534 µs ± 1.82 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
%timeit test.notselfn()

271 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [13]:
(np.arange(-50, 100, 1))[50:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
a = np.arange(0, 10, 1)

In [21]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a[[2, 4]] = np.array([3, 5])

In [23]:
a

array([0, 1, 3, 3, 5, 5, 6, 7, 8, 9])

In [27]:
b = np.zeros((4, 3, 2))

In [34]:
b.shape[0::2]

SyntaxError: can't use starred expression here (1440287375.py, line 1)

In [45]:
a = np.array([1, 0, 1, 0, 1, 0])
a

array([1, 0, 1, 0, 1, 0])

In [55]:
def test(testarr):
    return testarr * 2

test(np.array([1, 0, 1, 0, 1, 0]))

array([2, 0, 2, 0, 2, 0])

In [ ]:
def test():
    return testarr * 2

test(np.array([1, 0, 1, 0, 1, 0]))

In [8]:
import time

time.time(),\
time.time() + 10

(1652474563.962738, 1652474573.962738)

In [15]:
import datetime

datetime.datetime(2011, 4, 25, ) + datetime

TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'module'

In [20]:
def exchangeable_value(budget, exchange_rate, spread, denomination):
    """

    :param budget: float - the amount of your money you are planning to exchange.
    :param exchange_rate: float - the unit value of the foreign currency.
    :param spread: int - percentage that is taken as an exchange fee.
    :param denomination: int - the value of a single bill.
    :return: int - maximum value you can get.
    """

    exchange_rate = exchange_rate + (spread / 100) * exchange_rate

    print(exchange_rate)

    return ((budget / exchange_rate) // denomination) * denomination

exchangeable_value(127.25, 1.20, 10, 20)

1.3199999999999998


80.0

In [22]:
for i in range(10):
    print(2 ** i)

1
2
4
8
16
32
64
128
256
512


In [23]:
sum([4, 5])

9

In [33]:
2 ** 8

256

In [34]:
sum([2 ** i for i in range(8)])

255

In [37]:

for number in range(65):
    if 1 <= number < 64:
        print(number)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63


In [40]:
def remove_suffix_ness(word):
    """Remove the suffix from the word while keeping spelling in mind.

    :param word: str - of word to remove suffix from.
    :return: str - of word with suffix removed & spelling adjusted.

    For example: "heaviness" becomes "heavy", but "sadness" becomes "sad".
    """

    return word[0: word.find("ness")]


remove_suffix_ness("sadness")

'sad'

In [41]:

deck_values = {f"{value}": value for value in range(2, 11)}

deck_values

{'2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10}

In [42]:
def value_of_card(card):
    """Determine the scoring value of a card.

    :param card: str - given card.
    :return: int - value of a given card.  See below for values.

    1.  'J', 'Q', or 'K' (otherwise known as "face cards") = 10
    2.  'A' (ace card) = 1
    3.  '2' - '10' = numerical value.
    """
    deck_values = {f"{value}": value for value in range(2, 11)}
    deck_values["A"] = 1
    for card in "JQL":
        deck_values[card] = 10

    return deck_values[card]

value_of_card("A")

10

In [43]:
"B" in "ABC"

True

In [46]:
from operator import eq

eq()

TypeError: eq expected 2 arguments, got 3

In [48]:
mean([3, 4])

NameError: name 'mean' is not defined

In [50]:
1 == 1 == 1

False

In [56]:
en = [1, 2, 3, 4, 5, 6]

for i, val in enumerate(en, 2:
    print(i)

TypeError: enumerate() takes at most 2 arguments (3 given)

In [59]:
lista = [1, 2, 3, 4, 5]

for i in lista:
    i += 1

print(lista)

[1, 2, 3, 4, 5]


In [61]:
scores = list(range(10))

len([score for score in scores if score > 5])

4

In [63]:
[score if score > 5 else 1 for score in scores]

[1, 1, 1, 1, 1, 1, 6, 7, 8, 9]

In [64]:
max(scores)

9

In [73]:
scores1 = list(range(0, 4))
names1 = ["Kalle", "Hobbe", "Bosse", "Lasse"]


scores1, names1

([0, 1, 2, 3], ['Kalle', 'Hobbe', 'Bosse', 'Lasse'])

In [82]:
for i, (score, name) in enumerate(zip(scores1, names1)):
    print(i, score, name)

0 0 Kalle
1 1 Hobbe
2 2 Bosse
3 3 Lasse


In [87]:
import numpy as np

a = np.linspace(0, 10, 25)

a = list(a)

list(map(round, a))

[0, 0, 1, 1, 2, 2, 2, 3, 3, 4, 4, 5, 5, 5, 6, 6, 7, 7, 8, 8, 8, 9, 9, 10, 10]

In [106]:
a = [1, 2, 3, 4]
b = [1, 2, 3]

a == b

False

In [146]:
SUBLIST = 3
SUPERLIST = 2
EQUAL = 1
UNEQUAL = 0


def sublist(list_one, list_two):
    if list_one == list_two:
        return EQUAL
    if list_one == []:
        return SUBLIST
    if list_two == []:
        return SUPERLIST

    for i in range(len(list_one) - len(list_two) + 1):
        if list_one[i: i + len(list_two)] == list_two:
            return SUPERLIST

    list_one, list_two = list_two, list_one

    for i in range(len(list_one) - len(list_two) + 1):
        if list_one[i: i + len(list_two)] == list_two:
            return SUBLIST
    
    
    return UNEQUAL

a = [1, 2, 3, 4]
b = [2, 3]



[1, 2, 3, 4] [2, 3]
[1, 2, 3, 4] [2, 3]


In [147]:
sublist(list(range(1000)) * 1000 + list(range(1000, 1100)), list(range(900, 1050)))

2

In [148]:
sublist(list(range(3, 200, 3)), list(range(15, 200, 15)))

0

In [149]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [152]:
a = "059"

list(a)

['0', '5', '9']

In [184]:
class Luhn:
    def __init__(self, card_num):        
        self.card_num = str(card_num).replace(" ", "")

    def valid(self):
        
        if len(self.card_num) <= 1:
            return False

        for character in self.card_num:
            if character not in list(range(0, 10)):
                return False

        card_num = list(map(int, list(self.card_num)))
        print(card_num)
        card_num = card_num[::-1]
        print(card_num)

        for i in range(1, len(card_num) - 1, 2):
            card_num[i] = 2 * card_num[i]
            print(card_num[i])
            if card_num[i] > 9:
                card_num[i] = card_num[i] - 9

            print(card_num[i])

        print(card_num, sum(card_num))

        if sum(card_num) % 10 == 0:
            return True
        return False



Luhn("59").valid()

False

In [179]:
a = "hejpodej"

a.strip(str)

AttributeError: type object 'str' has no attribute 'ascii'

In [183]:
for i in range(10):
    if i < 8:
        print(i)
    else:
        break
else:
    print("oops")

0
1
2
3
4
5
6
7


In [186]:
a = 3
b = 4
c = 5
d = 6

a ** 2, b ** 2, c ** 2, d ** 2

(9, 16, 25, 36)

In [ ]:
a < 1 / 3
b

1 / 3 < c < 3 / 3

In [ ]:
a + b + c = N

c = N - a - b

In [218]:
def triplets_with_sum(number):
    triplets = []
    for a in range(1, number // 3):
        for b in range(a, number // 2):
            c = a ** 2 + b ** 2
            if c ** 0.5 % 1 == 0:
                c = int(c ** 0.5)
                print(a, b, c)
                if a + b + c == number:
                    triplets.append([a, b, c])

    return triplets

triplets_with_sum(30000)

3 4 5
5 12 13
6 8 10
7 24 25
8 15 17
9 12 15
9 40 41
10 24 26
11 60 61
12 16 20
12 35 37
13 84 85
14 48 50
15 20 25
15 36 39
15 112 113
16 30 34
16 63 65
17 144 145
18 24 30
18 80 82
19 180 181
20 21 29
20 48 52
20 99 101
21 28 35
21 72 75
21 220 221
22 120 122
23 264 265
24 32 40
24 45 51
24 70 74
24 143 145
25 60 65
25 312 313
26 168 170
27 36 45
27 120 123
27 364 365
28 45 53
28 96 100
28 195 197
29 420 421
30 40 50
30 72 78
30 224 226
31 480 481
32 60 68
32 126 130
32 255 257
33 44 55
33 56 65
33 180 183
33 544 545
34 288 290
35 84 91
35 120 125
35 612 613
36 48 60
36 77 85
36 105 111
36 160 164
36 323 325
37 684 685
38 360 362
39 52 65
39 80 89
39 252 255
39 760 761
40 42 58
40 75 85
40 96 104
40 198 202
40 399 401
41 840 841
42 56 70
42 144 150
42 440 442
43 924 925
44 117 125
44 240 244
44 483 485
45 60 75
45 108 117
45 200 205
45 336 339
45 1012 1013
46 528 530
47 1104 1105
48 55 73
48 64 80
48 90 102
48 140 148
48 189 195
48 286 290
48 575 577
49 168 175
49 1200 1201
50 120 13

[[1200, 14375, 14425],
 [1875, 14000, 14125],
 [5000, 12000, 13000],
 [6000, 11250, 12750],
 [7500, 10000, 12500]]

In [216]:
import numpy as np

a = np.arange(0, 10000)
b = np.arange(0, 10000)

b = a ** 2 + b ** 2

b = (b ** 0.5).astype(int)

In [217]:
d = a + b + c

In [215]:
d[(d == 30000)]

array([], dtype=int64)

In [306]:
import numpy as np

def triplets_with_sum(number):
    triplets = []
    a = np.arange(1, number // 3 + 1)

    triples = []

    for b_int in range(1, number // 2 + 1):
        b = np.full(number // 3, b_int)
        c = (a ** 2 + b ** 2) ** 0.5
        c[c == c.astype(np.int64)]

        indices = c == c.astype(np.int64)

        for index in np.where(indices)[0]:
            triple = sorted([a[index], b[index], int(c[index])])
            if sum(triple) == number:
                if triple not in triples:
                    triples.append(triple)

    return triples

triplets_with_sum(30000)

[[7500, 10000, 12500],
 [6000, 11250, 12750],
 [5000, 12000, 13000],
 [1875, 14000, 14125],
 [1200, 14375, 14425]]

In [300]:
[12, 5, 13].sort()

In [249]:
np.full(100, 2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [308]:
for i in range(10, 0, -1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [310]:
import math
100 / 2, (math.sqrt(2)-1) * 100

(50.0, 41.42135623730952)

In [316]:
def triplets_with_sum(number):

    triplets = []
    for a in range(1, number // 3):
        for b in range(a, number // 2):
            if a + b + (a ** 2 + b ** 2) ** 0.5 == number:
                triplets.append([a, b, (a ** 2 + b ** 2) ** 0.5])

    return triplets

triplets_with_sum(30000)

[[1200, 14375, 14425.0],
 [1875, 14000, 14125.0],
 [5000, 12000, 13000.0],
 [6000, 11250, 12750.0],
 [7500, 10000, 12500.0]]