In [7]:
import numpy as np

In [1]:
class Test():
    def __init__(self):
        self.n = 1000

    def selfn(self):

        for i in range(10000):
            self.n = self.n = 1

    def notselfn(self):
        n = self.n

        for i in range(10000):
            n = n + 1


test = Test()

In [4]:
%timeit test.selfn()

534 µs ± 1.82 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
%timeit test.notselfn()

271 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [13]:
(np.arange(-50, 100, 1))[50:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
a = np.arange(0, 10, 1)

In [21]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a[[2, 4]] = np.array([3, 5])

In [23]:
a

array([0, 1, 3, 3, 5, 5, 6, 7, 8, 9])

In [27]:
b = np.zeros((4, 3, 2))

In [34]:
b.shape[0::2]

SyntaxError: can't use starred expression here (1440287375.py, line 1)

In [45]:
a = np.array([1, 0, 1, 0, 1, 0])
a

array([1, 0, 1, 0, 1, 0])

In [55]:
def test(testarr):
    return testarr * 2

test(np.array([1, 0, 1, 0, 1, 0]))

array([2, 0, 2, 0, 2, 0])

In [ ]:
def test():
    return testarr * 2

test(np.array([1, 0, 1, 0, 1, 0]))